version: '3.1'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: api_nginx_proxy
    ports:
      - "80:80"
    volumes:
    - ./docker/nginx/:/etc/nginx/conf.d/
  app:
    build:
      context: ./docker/app
    container_name: api_app

  db:
    container_name: api_database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - './api_database:/var/lib/postgresql/data'

  pgadmin:
    container_name: api_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@mail.com 
      PGADMIN_DEFAULT_PASSWORD: password
    ports: 
      - 8080:80
  

