version: '3.1'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: api_nginx_proxy
    ports:
      - "80:80"
    volumes:
    - ./docker/nginx/:/etc/nginx/conf.d/
  app:
    build:
      context: ./docker/app
    container_name: api_app
  db:
    image: mariadb
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mariadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_PORT=3306
     - PMA_USER=root
     - PMA_PASSWORD=example
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80

